### ISSUE TITLE
Link  "Suggest a change on this page" is broken

### ISSUE THREAD

**Issue by ecerulm** [apache/airflow-site#417]
For example [KubernetesPodOperator](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html) has "Suggest a change on this page" button at the bottom that points to

https://github.com/apache/airflow/edit/devel/docs/apache-airflow-providers-cncf-kubernetes/operators.rst

and it should be

https://github.com/apache/airflow/edit/master/docs/apache-airflow-providers-cncf-kubernetes/operators.rst

so the broken links points to "devel" and it should point to "master" instead

**Comment by potiuk** [comment]
@mik-laj - I guess this is part of the Sphinx-theme? Where is it hosted?

**Comment by mik-laj** [comment]
Here we should set a valid version
https://github.com/apache/airflow/blob/04454d512eb3f117154868668ed036d5e7697040/docs/conf.py#L80

**Comment by potiuk** [comment]
It was a bit different problem, the 'devel' was hardcoded in `html_context`  - it also applies to 'apache-airflow' and 'docker-stack' . And I replaced it with `main` rather than package version - no matter what version we get it from, the Github PR should be always targeted to `main` - that's our rule.

Will be fixed in https://github.com/apache/airflow/pull/16405

**Comment by potiuk** [comment]
The fix is merged. With next doc releases it should be fixed.

**Comment by yiannis-had** [comment]
This issue still happens. Use this and click on the suggest a change button: https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/python/index.html

**Comment by potiuk** [comment]
Nope. This is a different issue that is tracked separately - related to API pages having the button as well where they should not. You can search issues to find it.
